spring.application.name=api-financeira
server.servlet.context-path=/api-financeira
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/apiFinanceiraDB
spring.datasource.username=xxxxx
spring.datasource.password=xxxxx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuracoes no pool de conexoes
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# Habilitando Virtual Threads
spring.threads.virtual.enabled=true

# No Json nao retornar a property quando valor NULL
spring.jackson.default-property-inclusion=non_null

# Ignorar properties que estao faltando no Json e preencher com NULL
spring.jackson.deserialization.fail-on-missing-creator-properties=false

# Quando atributos ausentes interpretar como nulos/vazios
spring.jackson.deserialization.fail-on-null-creator-properties=false